version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 26_webapp_21a
      MYSQL_USER: 26_webapp_21
      MYSQL_PASSWORD: 5IjS9piA
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
